var namnsdagar = {
"1.1" : "Nyårsdagen",
"2.1" : "Aapeli, Gerhard och Gert",
"3.1" : "Elmeri, Elmer, Elmo, och Helmer",
"4.1" : "Ruut och Rut",
"5.1" : "Lea och Leea",
"6.1" : "Harri, Harry och Harriet",
"7.1" : "Aukusti, Aku, August och Augusta",
"8.1" : "Hilppa, Titta och Gunnar",
"9.1" : "Veikko, Veli, Veijo och Bror",
"10.1" : "Nyyrikki och Sigrud",
"11.1" : "Kari, Karri och Osvald",
"12.1" : "Toini och Eivor",
"13.1" : "Nuutti och Knut",
"14.1" : "Sakari, Saku och Zacharias",
"15.1" : "Solja och Doris",
"16.1" : "Ilmari, Ilmo, Gudmund och Germund",
"17.1" : "Toni, Anttoni, Antto, Anton, Tony och Antonia",
"18.1" : "Laura",
"19.1" : "Heikki, Henrik, Henrikki, Henri, Henry, Henrika och Henrietta",
"20.1" : "Henna, Henni, Henriikka, Sebastian och Fabian",
"21.1" : "Aune, Oona, Auni, Agnes och Agneta",
"22.1" : "Visa och Fridolf",
"23.1" : "Eine, Eini, Enni, Ingegerd och Ingela",
"24.1" : "Senja och Jarl",
"25.1" : "Paavo, Pauli, Paavali och Paul",
"26.1" : "Joonatan och Jonatan",
"27.1" : "Viljo och Folke",
"28.1" : "Kaarlo, Kalle, Kaarle, Mies, Karl och Carola",
"29.1" : "Valtteri, Valter och Volter",
"30.1" : "Irja, Gunnel och Gunilla",
"31.1" : "Alli, Alfhild och Alfa",
"1.2" : "Riitta och Berit",
"2.2" : "Aamu, Jemina och Disa",
"3.2" : "Valo och Hugo",
"4.2" : "Armi, Ronja och My",
"5.2" : "Asser och Ture",
"6.2" : "Terhi, Teija, Tiia, Tea, Terhikki, Dorotea, Dora och Dorrit",
"7.2" : "Riku, Rikhard, Rikard och Dick",
"8.2" : "Laina och Rigmor",
"9.2" : "Raija, Raisa och Bodil",
"10.2" : "Elina, Elna, Ella, Ellen och Elin",
"11.2" : "Talvikki, Isabella och Isa",
"12.2" : "Elma och Elmi",
"13.2" : "Sulo, Sulho och Algot",
"14.2" : "Voitto, Valentin och Tino",
"15.2" : "Sipi, Sippo och Sigfrid",
"16.2" : "Kai och Kaj",
"17.2" : "Väinö, Väinämö, Carita och Rita",
"18.2" : "Kaino och Tyra",
"19.2" : "Eija och Fritjof",
"20.2" : "Heli, Helinä, Heljä, Hely och Ragnborg",
"21.2" : "Keijo, Alf och Alva",
"22.2" : "Tuulikki, Tuuli, Tuulia, Hildur och Hilda",
"23.2" : "Aslak och Bjarne",
"24.2" : "Matti, Matias, Mattias och Mats",
"25.2" : "Tuija, Tuire och Jessica",
"26.2" : "Nestori, Ingvar och Ingvald",
"27.2" : "Torsti och Torsten",
"28.2" : "Onni, Rune och Runa",
"29.2" : "Skottårsdagen",
"1.3" : "Alpo, Alvi, Alpi och Albin",
"2.3" : "Virve, Virva och Fanny",
"3.3" : "Kauko och Torbjörn",
"4.3" : "Ari, Arsi, Atro, Adrian och Atle",
"5.3" : "Laila och Leila",
"6.3" : "Tarmo, Rudolf och Rolf",
"7.3" : "Tarja, Taru och Gudrun",
"8.3" : "Vilppu, Filip och Filippa",
"9.3" : "Auvo och Edvin",
"10.3" : "Aurora, Aura och Auri",
"11.3" : "Kalervo, Torgny och Torkel",
"12.3" : "Reijo, Reko, Gregorius, Greger och Grels",
"13.3" : "Erno, Tarvo, Ernesti och Ernst",
"14.3" : "Matilda och Tilda",
"15.3" : "Risto och Kristoffer",
"16.3" : "Ilkka och Herbert",
"17.3" : "Kerttu, Kerttuli, Gertrud och Trude",
"18.3" : "Eetu och Edvard",
"19.3" : "Jooseppi, Juuso, Joosef, Josefiina, Josef och Josefina",
"20.3" : "Aki, Joakim och Kim",
"21.3" : "Pentti, Bengt, Bengta och Benita",
"22.3" : "Vihtori, Viktor och Viktoria",
"23.3" : "Akseli och Axel",
"24.3" : "Kaapo, Gabriel, Kaapro, Kaappo och Gabriella",
"25.3" : "Aija, Gunvor och Gunnevi",
"26.3" : "Manu, Immanuel, Manne, Immo och Emanuel",
"27.3" : "Sauli, Saul och Torvald",
"28.3" : "Armas och Sune",
"29.3" : "Joonas, Jouni, Joni, Joona, Jonne, Jonni och Jonas",
"30.3" : "Usko, Tage och Guy",
"31.3" : "Irma, Irmeli och Irmelin",
"1.4" : "Raita, Pulmu och Harald",
"2.4" : "Pellervo och Vidar",
"3.4" : "Sampo, Veeti och Ferdinand",
"4.4" : "Ukko och Odin",
"5.4" : "Irene, Irina, Ira, och Iro",
"6.4" : "Vilho, Ville, Viljami, Vilhelm, Vili, Jami och William",
"7.4" : "Allan och Ahvo",
"8.4" : "Suoma, Suometar och Rea",
"9.4" : "Elias, Eelis, Eljas och Eliel",
"10.4" : "Tero och Tryggve",
"11.4" : "Verna",
"12.4" : "Julius, Julia, Juliaana och Juliana",
"13.4" : "Tellervo och Etel",
"14.4" : "Taito och Ruben",
"15.4" : "Linda, Tuomi och Linn",
"16.4" : "Jalo, Patrik och Patricia",
"17.4" : "Otto",
"18.4" : "Valto, Valdemar och Volmar",
"19.4" : "Pälvi, Pilvi, Bernhard och Bernt",
"20.4" : "Lauha och Arla",
"21.4" : "Anssi, Anselmi och Camilla",
"22.4" : "Alina",
"23.4" : "Yrjö, Jyrki, Jyri, Yrjänä, Jori, Georg, Göran, Örjan, Jöran, Jörgen och Jörn",
"24.4" : "Pertti, Albert, Altti och Albertina",
"25.4" : "Markku, Markus och Marko",
"26.4" : "Terttu, Teresa, Teresia och Terese",
"27.4" : "Merja, Engelbrekt och Engelbert",
"28.4" : "Ilpo, Ilppo, Tuure och Ture",
"29.4" : "Teijo och Henning",
"30.4" : "Mirja, Mirva, Mira, Miia, Mia, Mirjami, Mirka och Mirkka",
"1.5" : "Vappu, Valpuri och Valborg",
"2.5" : "Vuokko, Viivi, Vivan och Vivi",
"3.5" : "Outi och Linus",
"4.5" : "Ruusu, Roosa och Rosa",
"5.5" : "Maini och Ulrik",
"6.5" : "Ylermi, Frej, Frejvid och Freja",
"7.5" : "Helmi, Kastehelmi och Tua",
"8.5" : "Heino och Åke",
"9.5" : "Timo och Dennis",
"10.5" : "Aino, Aina, Aini och Ainikki",
"11.5" : "Osmo, Kennet, Kent",
"12.5" : "Lotta, Charlotta och Lotten",
"13.5" : "Kukka, Floora och Flora",
"14.5" : "Tuula och Edit",
"15.5" : "Sofia, Sonja och Sohvi",
"16.5" : "Esteri, Essi och Ester",
"17.5" : "Maila, Maili, Mailis, Rebekka, Rebecka och Hagar",
"18.5" : "Erkki, Eero, Eerikki, Eerika, Erik, Jerker och Erika",
"19.5" : "Emilia, Emma, Emmi, Milla, Milja, Milka, Amalia och Mili",
"20.5" : "Lilja, Karoliina, Lilli och Lilian",
"21.5" : "Kosti, Konsta, Konstantin och Conny",
"22.5" : "Hemminki, Hemmo och Hemming",
"23.5" : "Lyydia, Lyyli och Lydia",
"24.5" : "Tuukka, Touko och Alarik",
"25.5" : "Urpo och Urban",
"26.5" : "Vilhelmiina, Minna, Vilma, Miina, Mimmi och Vilhelmina",
"27.5" : "Ritva och Ingeborg",
"28.5" : "Alma",
"29.5" : "Oiva, Oivi, Olivia, Orvar, Oliver och Olivia",
"30.5" : "Pasi och Rurik",
"31.5" : "Helka, Helga och Helge",
"1.6" : "Teemu, Nikodemus och Rabbe",
"2.6" : "Venla och Vendla",
"3.6" : "Orvokki och Viola",
"4.6" : "Toivo och Selim",
"5.6" : "Sulevi och Stig",
"6.6" : "Kustaa, Kyösti, Kustavi, Gustav, Gösta, Gustava",
"7.6" : "Suvi, Robert, Roope, Robert och Robin",
"8.6" : "Salomo, Salomon, Kjell och Kettil",
"9.6" : "Ensio och Daga",
"10.6" : "Seppo och Svante",
"11.6" : "Impi, Immi och Hjördis",
"12.6" : "Esko och Eskil",
"13.6" : "Raili, Raila, Åsa och Aslög",
"14.6" : "Kielo, Pihla och Tord",
"15.6" : "Vieno och Viena, Moona, Mona, Monika",
"16.6" : "Päivi, Päivikki, Päivä och Eugen",
"17.6" : "Urho, Birger och Börje",
"18.6" : "Tapio och Ingolf",
"19.6" : "Siiri, Sigri och Siri",
"20.6" : "Into och Inga",
"21.6" : "Ahti, Ahto, Ingemar, Ingmar och Inge",
"22.6" : "Paula, Liina, Pauliina, Paulina och Lina",
"23.6" : "Aatto, Aatu, Aadolf och Adolf",
"24.6" : "Johannes, Juhani, Juha, Juho, Jukka, Jussi, Janne, Jani, Juhana, Johannes, Johan, Jan, Jon, John, Johnny och Jens",
"25.6" : "Uuno och Uno",
"26.6" : "Jorma, Jarmo, Jarkko, Jarno, Jere, Jeremias och Viveka",
"27.6" : "Elviira, Elvi och Elvira",
"28.6" : "Leo och Leopold",
"29.6" : "Pietari, Pekka, Petri, Petra, Petteri, Pekko, Peter, Per, Petter, Petra och Pernilla",
"30.6" : "Päiviö, Päivö och Leif",
"1.7" : "Aaro, Aaron och Kasimir",
"2.7" : "Maria, Mari, Maija, Meeri, Maaria, Marika, Maiju, Maikki, Kukka-Maaria, Maja, Maj och Mary",
"3.7" : "Arvo, Egil, Ejvind och Öjvind",
"4.7" : "Ulla, Ulpu och Ulrika",
"5.7" : "Unto, Untamo och Ulf",
"6.7" : "Esa, Esaias och Halvar",
"7.7" : "Klaus, Launo och Klas",
"8.7" : "Turo, Turkka, Tor, Tore och Tora",
"9.7" : "Ilta, Jasmin, Nanna och Nanny",
"10.7" : "Saima och Saimi",
"11.7" : "Elli, Noora, Nelli, Eleonoora, Eleonora, Nora, Leonora och Elinor",
"12.7" : "Hermanni, Herkko och Herman",
"13.7" : "Ilari, Lari och Joel",
"14.7" : "Aliisa, Alisa och Alice",
"15.7" : "Rauni, Rauna, Ragnhild, Ragni och Ragna",
"16.7" : "Reino och Reinhold",
"17.7" : "Ossi och Ossian",
"18.7" : "Riikka, Frederik, Fred och Frederika",
"19.7" : "Saara, Sari, Salli, Salla, Sara och Sally",
"20.7" : "Marketta, Maarit, Reeta, Maaret, Reetta, Margareeta, Margereta, Margit, Marit, Greta och Gretel",
"21.7" : "Johanna, Hanna, Jenni, Jonna, Jenna, Hannele, Hanne, Joanna, Johanna, Jenry, Hanna och Hannele",
"22.7" : "Leena, Leeni, Lenita, Matleena, Magdaleena, Malin och Lena",
"23.7" : "Oili och Olga",
"24.7" : "Kristiina, Kirsti, Tiina, Kirsi, Krista, Kiia, Kristina, Kerstin, Kristel, Kia, Stina och Tina",
"25.7" : "Jaakko, Jaakoppi, Jaakob, Jakob, Jimi och Jim",
"26.7" : "Martta och Marta",
"27.7" : "Heidi",
"28.7" : "Atso och Håkan",
"29.7" : "Olavi, Olli, Uolevi, Uoti, Olof, Olav, Ola, Ole och Olle",
"30.7" : "Asta",
"31.7" : "Helena och Elena",
"1.8" : "Maire, Gerda och Gerd",
"2.8" : "Kimmo och Holger",
"3.8" : "Linnea, Nea, Neea och Vanamo",
"4.8" : "Veera och Vera",
"5.8" : "Salme, Sanelma och Gurli",
"6.8" : "Toimi, Keimo och Sixten",
"7.8" : "Lahja och Yrsa",
"8.8" : "Sylvi, Sylvia och Silva",
"9.8" : "Erja, Eira och Natalie",
"10.8" : "Lauri, Lasse, Lassi och Lars",
"11.8" : "Sanna, Sanni, Susanna och Susanne",
"12.8" : "Klaara och Klara",
"13.8" : "Jesse och Alfons",
"14.8" : "Onerva, Kanerva och Svea",
"15.8" : "Marjatta, Marja, Jaana, Marjo, Marjut, Marjaana, Marjukka, Marita, Maritta, Marianne, Marianna och Marlene",
"16.8" : "Aulis och Brynolf",
"17.8" : "Verneri, Verner och Veronika",
"18.8" : "Leevi och Bo",
"19.8" : "Mauno, Maunu, Magnus och Måns",
"20.8" : "Samuli, Sami, Samuel, Samu och Sam",
"21.8" : "Soini, Veini och Sven",
"22.8" : "Iivari, Iivo och Ivo",
"23.8" : "Varma, Signe och Signhild",
"24.8" : "Perttu, Bertel, Bertil och Berta",
"25.8" : "Loviisa, Lovisa och Louise",
"26.8" : "Ilma, Ilmi, Ilmatar, Märta och Märit",
"27.8" : "Rauli, Ralf och Rufus",
"28.8" : "Tauno och Hilding",
"29.8" : "Iines, Iina, Inari, Ines och Ina",
"30.8" : "Eemil, Eemeli och Emil",
"31.8" : "Arvi och Arvid",
"1.9" : "Pirkka och Gottfrid",
"2.9" : "Sinikka, Sini och Synnöve",
"3.9" : "Soili, Soile, Soila och Solveig",
"4.9" : "Ansa och Roland",
"5.9" : "Roni, Mainio, Ragnvald, Ronald och Ronny",
"6.9" : "Asko och Felix",
"7.9" : "Miro, Arho, Arhippa, Regina och Roy",
"8.9" : "Taimi, Göte och Göta",
"9.9" : "Eevert, Isto och Evert",
"10.9" : "Kalevi, Kaleva och Östen",
"11.9" : "Aleksanteri, Santeri, Ali, Ale, Aleksandra, Alexander, Alex, Alexandra och Sandra",
"12.9" : "Valma, Vilja och Dagny",
"13.9" : "Orvo och Ylva",
"14.9" : "Iida och Ida",
"15.9" : "Sirpa och Runar",
"16.9" : "Hellevi, Hillevi, Hille, Hilla och Helvig",
"17.9" : "Aili, Aila, Hildegard och Hildegerd",
"18.9" : "Tyyne, Tytti, Tyyni och Pamela",
"19.9" : "Reija och Torborg",
"20.9" : "Varpu, Vaula och Erna",
"21.9" : "Mervi, Gunborg och Gunlög",
"22.9" : "Mauri, Mauriz och Moriz",
"23.9" : "Mielikki och Teklai",
"24.9" : "Alvar och Auno",
"25.9" : "Kullervo och Sigvard",
"26.9" : "Kuisma och Finn",
"27.9" : "Vesa och Torolf",
"28.9" : "Arja, Leonard och Lennart",
"29.9" : "Mikael, Mikko, Mika, Miika, Miikka, Miska och Mikaela",
"30.9" : "Sorja, Sirja och Roger",
"1.10" : "Rauno, Rainer, Raine, Raino, Ragnar och Rainer",
"2.10" : "Valio och Ludvig",
"3.10" : "Raimo och Evald",
"4.10" : "Saila, Saija, Frans och Frank",
"5.10" : "Inkeri, Inka, Ingrid och Inger",
"6.10" : "Minttu, Pinja och Bruno",
"7.10" : "Pirkko, Pirjo, Piritta, Pirita, Birgitta, Brita, Britta, Britt och Birgit",
"8.10" : "Hilja och Peik",
"9.10" : "Ilona och Marina",
"10.10" : "Aleksi, Aleksis och Alexis",
"11.10" : "Otso, Ohto och Björn",
"12.10" : "Aarre, Aarto och Valfrid",
"13.10" : "Taina, Tanja, Taija, Ebbe och Ebba",
"14.10" : "Elsa, Else, Elsi och Ilse",
"15.10" : "Helvi, Heta, Hedvig och Hedda",
"16.10" : "Sirkka, Sirkku och Stella",
"17.10" : "Saini, Saana, Vesta, Diana",
"18.10" : "Satu, Säde och Saga",
"19.10" : "Uljas och Viking",
"20.10" : "Kauno, Kasperi, Kasper och Jesper",
"21.10" : "Ursula",
"22.10" : "Anja, Anita, Anniina och Anitta",
"23.10" : "Severi, Severin och Sören",
"24.10" : "Asmo och Rasmus",
"25.10" : "Sointu och Yvonne",
"26.10" : "Amanda, Niina, Manta, Nina och Ninni",
"27.10" : "Helli, Hellä, Hellin, Helle och Sabina",
"28.10" : "Simo och Simon",
"29.10" : "Alfred och Urmas",
"30.10" : "Eila och Jennifer",
"31.10" : "Artturi, Arto, Arttu och Artur",
"1.11" : "Pyry, Lyly, Gun och Gunhild",
"2.11" : "Topi, Topias och Tobias",
"3.11" : "Terho och Erland",
"4.11" : "Hertta och Carina",
"5.11" : "Reima och Torhild",
"6.11" : "Kustaa Aadolf, Gustav och Adolf",
"7.11" : "Taisto och Glenn",
"8.11" : "Aatos och Styrbjörn",
"9.11" : "Teuvo, Teodor och Theo",
"10.11" : "Martti, Martin, Mårten och Martina",
"11.11" : "Panu och Boris",
"12.11" : "Virpi, Konrad och Kurt",
"13.11" : "Ano, Kristian och Krister",
"14.11" : "Iiris och Iris",
"15.11" : "Janika, Janita, Janina, Janette, Jannika och Jeanette",
"16.11" : "Aarne, Aarno, Aarni, Arne, Arnold och Arna",
"17.11" : "Eino, Einari, Einar och Enar",
"18.11" : "Tenho, Jousia och Max",
"19.11" : "Elisabet, Liisa, Eliisa, Elisa, Elise, Liisi, Lisa, Lisen, Lisbet och Elise",
"20.11" : "Jalmari, Jari, Hjalmar och Pontus",
"21.11" : "Hilma",
"22.11" : "Silja, Selja och Cecilia",
"23.11" : "Ismo, Yngve, Yngvar",
"24.11" : "Lempi, Lemmikki, Sivi och Siv",
"25.11" : "Katri, Kaisa, Kaija, Katja, Kaarina, Katariina, Katriina, Kati, Kaisu, Riina, Katarina, Karin och Kajsa",
"26.11" : "Sisko och Dagmar",
"27.11" : "Hilkka, Astrid och Estrid",
"28.11" : "Heini och Sten",
"29.11" : "Aimo och Edgar",
"30.11" : "Antti, Antero, Atte, Anders, Andreas, Andre och Andrea",
"1.12" : "Oskari och Oskar",
"2.12" : "Anelma, Unelma, Beata och Beatrice",
"3.12" : "Vellamo, Meri och Urda",
"4.12" : "Airi, Aira, Barbara och Barbro",
"5.12" : "Selma",
"6.12" : "Niilo, Nikolai, Niko, Niklas och Nils",
"7.12" : "Sampsa, Agata, Agda och Ågot",
"8.12" : "Kyllikki, Kylli, Magnhild och Magna",
"9.12" : "Anna, Anne, Anni, Anu, Annikki, Anneli, Annukka, Annika och Annette",
"10.12" : "Jutta och Judit",
"11.12" : "Taneli, Tatu, Daniel, Dan och Daniela",
"12.12" : "Tuovi och Tove",
"13.12" : "Seija och Lucia",
"14.12" : "Jouko och Ove",
"15.12" : "Heimo och Sverker",
"16.12" : "Auli, Aulikki, Aada, Ada och Adele",
"17.12" : "Raakel och Rakel",
"18.12" : "Aapo, Aappo, Rami och Abraham",
"19.12" : "Iikka, Iiro, Iisakki, Isko och Isak",
"20.12" : "Benjamin, Kerkko, Ben och Benny",
"21.12" : "Tuomas, Tuomo, Tommi, Tomi, Tomas, Tom och Tommy",
"22.12" : "Raafael och Rafael",
"23.12" : "Senni och Elof",
"24.12" : "Aatami, Eeva, Eevi, Eveliina, Adam och Eva",
"25.12" : "Juldagen",
"26.12" : "Tapani, Teppo, Tahvo, Stefan och Staffan",
"27.12" : "Hannu, Hannes och Hans",
"28.12" : "Piia och Pia",
"29.12" : "Rauha och Frida",
"30.12" : "Daavid, Taavetti, Taavi och David",
"31.12" : "Sylvester och Silvo"
};
